# Generated by Django 4.2.4 on 2023-11-22 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('quiz_image', models.ImageField(blank=True, null=True, upload_to='quiz_images/')),
                ('correct_quiz_users', models.ManyToManyField(related_name='correct_quiz', to=settings.AUTH_USER_MODEL)),
                ('write_quiz_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='write_quiz', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_answer', models.BooleanField(default=False)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='QUIZ.quiz')),
            ],
        ),
    ]
