# Generated by Django 4.2.4 on 2023-11-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACCOUNTS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rate_image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
